### ISSUE TITLE
Position of helper icons fixed

### ISSUE THREAD

**Issue by MeganBeckett** [cwthom/shinyhelper#18]
Hi there

Thanks for this package - I've found it very helpful for making my shiny apps more user friendly.

I have  a question about the fixed position of the helper icons as they often float over other elements. See the screenshot below.

![Screenshot from 2020-04-28 10-03-19](https://user-images.githubusercontent.com/3185323/80462944-be788f00-8937-11ea-962d-67a0f0e39d71.png)

I've tried playing around with the css in Developer Tools, but no luck yet. Any idea how to fix this so that they don't float?

Thanks!

**Comment by cwthom** [comment]
Hi @MeganBeckett 

Thanks for this - I think it comes down to the `z-index` property of the `div` containing the icon. If you pass a value in through the `style` argument of `helper` then you should be able to set how far back in the depth of the page it sits.

The default is 900, which is further forward than most things and I think is why it's floating over your other elements. For your example you'd need to set the z-index to be something between the value for your blue panel and the value for your footer.

Let me know how you get on, it may be that this doesn't work and I'll think again!

**Comment by gadepallivs** [comment]
I'm facing the same problem, not sure how to pass the z-index appreciate if you can share an example. Here is my code that results in helper far from the action button and does not respond on click. Appreciate if you can suggest a fix. Below is a reproducible example

``` r
library(shiny)
ui <- fluidPage(
  shinyhelper::helper(shiny::actionButton("go", "click me!"),
         #'z-index' = 80,
         icon = "exclamation",
         colour = "red",
         type = "markdown",
         content = "ClickHelp")
)
server <- function(input, output, session) {
}
shinyApp(ui, server)

```
<sup>Created on 2022-01-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by cwthom** [comment]
Hi @gadepallivs , for z-index or other CSS properties, you need to pass it through in the style argument e.g 
```
style = "z-index: 80;"
```

**Comment by gadepallivs** [comment]
Hi, thank you for the quick response. Still the exclamation is in the same location, far from the button like in the pic above. Do I need to update my package ? I;m on mac os Big Sur

**Comment by cwthom** [comment]
Oh I see, you don't want z-index then, that's about depth into the page.

The helper icon will appear at the top right corner of the parent element i.e. the thing that the helper lives in. In your example this is just the whole fluidPage, which is why it appears in the top right corner, but if you put it in a column with a set width, then you should be okay.
