### ISSUE TITLE
No need to specify use_shinyhelper() if useShinyjs() already called

### ISSUE THREAD

**Issue by avisionh** [cwthom/shinyhelper#2]
Hi Chris,

Another one from me! Like the previous one, not an issue per se - more of a minor note.

You menetioned that you need to call *use_shinyhelper()* in the **ui.R** script. This isn't entirely necessary if you already call *useShinyjs()* from what I've found.

I know you mentioned that *use_shinyhelper* is a wrapper for *useShinyjs()* so it is implicit that if you already call *useShinyjs()*, then there is no need to call *use_shinyhelper()*. Do you think it is worth making this explicit though?

Thanks,
Avision

**Comment by avisionh** [comment]
Oh, and let me know if this is the wrong place to post these suggestions!

**Comment by cwthom** [comment]
Hi Avision,

Thanks for raising this. The reason for having a wrapper function is to keep the package reasonably self-contained. Without it, as you say I would need the user to call `shinyjs::useShinyjs()`, which means I would need to assume they read all the documentation and did that, or I would have to export that function in the shinyhelper package. I think it's more convenient to have a wrapper, and it has the added bonus that I can give it a new name to describe the use I'm putting it to.

I don't think it has any real overheads in terms of performance, so for the purposes of keeping shinyhelper self-contained I'll leave it as it is.

Cheers,
Chris
